version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Berlin
    labels:
      - dependencies
      - github_actions
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:15"
      timezone: Europe/Berlin
    labels:
      - dependencies
      - python
    groups:
      python:
        patterns:
          - "*"
