"""Localized names for Fitness-created devices."""

from .const import SUPPORTED_LANGUAGES

DEVICE_NAMES = {'en': {'evaluation': 'Evaluation', 'live': 'Live workout', 'sleep': 'Recovery', 'workout': 'Workouts', 'recovery': 'Recovery', 'wellness': 'Health metrics'}, 'el': {'evaluation': 'Αξιολόγηση', 'live': 'Ζωντανή προπόνηση', 'sleep': 'Αποκατάσταση', 'workout': 'Προπονήσεις', 'recovery': 'Αποκατάσταση', 'wellness': 'Μετρήσεις υγείας'}, 'de': {'evaluation': 'Auswertung', 'live': 'Live-Training', 'sleep': 'Erholung', 'workout': 'Trainings', 'recovery': 'Erholung', 'wellness': 'Gesundheitswerte'}, 'fr': {'evaluation': 'Évaluation', 'live': 'Entraînement en direct', 'sleep': 'Récupération', 'workout': 'Entraînements', 'recovery': 'Récupération', 'wellness': 'Mesures de santé'}, 'es': {'evaluation': 'Evaluación', 'live': 'Entrenamiento en directo', 'sleep': 'Recuperación', 'workout': 'Entrenamientos', 'recovery': 'Recuperación', 'wellness': 'Métricas de salud'}, 'it': {'evaluation': 'Valutazione', 'live': 'Allenamento in tempo reale', 'sleep': 'Recupero', 'workout': 'Allenamenti', 'recovery': 'Recupero', 'wellness': 'Metriche salute'}, 'pt': {'evaluation': 'Avaliação', 'live': 'Treino ao vivo', 'sleep': 'Recuperação', 'workout': 'Treinos', 'recovery': 'Recuperação', 'wellness': 'Métricas de saúde'}, 'nl': {'evaluation': 'Evaluatie', 'live': 'Live training', 'sleep': 'Herstel', 'workout': 'Trainingen', 'recovery': 'Herstel', 'wellness': 'Gezondheidsmetingen'}, 'pl': {'evaluation': 'Ocena', 'live': 'Trening na żywo', 'sleep': 'Regeneracja', 'workout': 'Treningi', 'recovery': 'Regeneracja', 'wellness': 'Wskaźniki zdrowotne'}, 'ru': {'evaluation': 'Оценка', 'live': 'Тренировка в реальном времени', 'sleep': 'Восстановление', 'workout': 'Тренировки', 'recovery': 'Восстановление', 'wellness': 'Показатели здоровья'}, 'uk': {'evaluation': 'Оцінка', 'live': 'Тренування наживо', 'sleep': 'Відновлення', 'workout': 'Тренування', 'recovery': 'Відновлення', 'wellness': 'Показники здоров’я'}, 'tr': {'evaluation': 'Değerlendirme', 'live': 'Canlı antrenman', 'sleep': 'Toparlanma', 'workout': 'Antrenmanlar', 'recovery': 'Toparlanma', 'wellness': 'Sağlık ölçümleri'}, 'zh': {'evaluation': '评估', 'live': '实时训练', 'sleep': '恢复', 'workout': '训练记录', 'recovery': '恢复', 'wellness': '健康指标'}, 'ja': {'evaluation': '評価', 'live': 'ライブトレーニング', 'sleep': 'リカバリー', 'workout': 'ワークアウト', 'recovery': 'リカバリー', 'wellness': '健康指標'}, 'ko': {'evaluation': '평가', 'live': '실시간 운동', 'sleep': '회복', 'workout': '운동 기록', 'recovery': '회복', 'wellness': '건강 지표'}}

def language_code(value: str | None) -> str:
    code = str(value or "en").lower().split("-")[0].split("_")[0]
    return code if code in SUPPORTED_LANGUAGES else "en"

def device_name(language: str | None, kind: str) -> str:
    code = language_code(language)
    return DEVICE_NAMES.get(code, DEVICE_NAMES["en"])[kind]
