from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
README = (ROOT / "README.md").read_text(encoding="utf-8")


def test_tldr_is_near_top():
    assert "## TL;DR" in README
    assert README.index("## TL;DR") < 3000


def test_tldr_explains_deterministic_vs_ai():
    start = README.index("## TL;DR")
    block = README[start:start + 6000]
    compact = " ".join(block.split())
    assert "AI is only an interpretation layer" in compact
    assert "never generated by AI" in compact
    assert "HA-ANT-Plus" in compact
