from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
MANAGER = (ROOT / "custom_components/fitness/manager.py").read_text(encoding="utf-8")
SENSOR = (ROOT / "custom_components/fitness/sensor.py").read_text(encoding="utf-8")
DASH = (ROOT / "custom_components/fitness/dashboard.py").read_text(encoding="utf-8")
JS = (ROOT / "custom_components/fitness/frontend/fitness-dashboard.js").read_text(encoding="utf-8")
README = (ROOT / "README.md").read_text(encoding="utf-8")

def test_reconciled_beta1_files():
    assert '"available_components": readiness.get("available_components")' in SENSOR
    assert '"available_components": available' in MANAGER
    assert "Δεν υπάρχουν ακόμη αρκετές" in MANAGER
    assert "_sleep_as_android_live_events" in MANAGER
    assert "record_from_event_history(" in MANAGER
    a = re.search(r'FITNESS_DASHBOARD_VERSION = "([^"]+)"', JS)
    b = re.search(r'_RESOURCE_URL = f".*?\\?v=([^"]+)"', DASH)
    assert a and b and a.group(1) == b.group(1) == "2026.8.10.5"
    assert "## TL;DR" in README
    assert "AI is only an interpretation layer" in README
    assert "never generated by AI" in README
    assert "HA-ANT-Plus" in README
    assert "## Fitness dashboard" in README
    assert "Community dashboards" in README
    assert "/fitness/frontend/fitness-dashboard.js" in README
    assert "OpenStreetMap" in README
