"""Registration point for physical-device archive adapters."""
from __future__ import annotations

from .bangle import ARCHIVE_ADAPTER as BANGLE_JS_ARCHIVE_ADAPTER
from .cycplus_adapter import ARCHIVE_ADAPTER as CYCPLUS_M1_ARCHIVE_ADAPTER
from .garmin import ARCHIVE_ADAPTER as GARMIN_ARCHIVE_ADAPTER
from .hplus import ARCHIVE_ADAPTER as HPLUS_ARCHIVE_ADAPTER
from .huami_keyed.adapters import ARCHIVE_ADAPTERS as HUAMI_KEYED_ARCHIVE_ADAPTERS
from .miband1 import ARCHIVE_ADAPTER as MIBAND1_ARCHIVE_ADAPTER
from .miband2 import ARCHIVE_ADAPTER as MIBAND2_ARCHIVE_ADAPTER
from .ultrahuman import ARCHIVE_ADAPTER as ULTRAHUMAN_AIR_ARCHIVE_ADAPTER
from .zetime import ARCHIVE_ADAPTER as ZETIME_ARCHIVE_ADAPTER
from .xiaomi_hr_broadcast import ARCHIVE_ADAPTERS as XIAOMI_HR_BROADCAST_ADAPTERS

ARCHIVE_ADAPTERS = (
    BANGLE_JS_ARCHIVE_ADAPTER,
    CYCPLUS_M1_ARCHIVE_ADAPTER,
    GARMIN_ARCHIVE_ADAPTER,
    HPLUS_ARCHIVE_ADAPTER,
    *HUAMI_KEYED_ARCHIVE_ADAPTERS,
    MIBAND1_ARCHIVE_ADAPTER,
    MIBAND2_ARCHIVE_ADAPTER,
    ULTRAHUMAN_AIR_ARCHIVE_ADAPTER,
    ZETIME_ARCHIVE_ADAPTER,
    *XIAOMI_HR_BROADCAST_ADAPTERS,
)
